# Use a lightweight Python image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy all files
COPY . /app

# Install dependencies
RUN pip install -r requirements.txt

# Expose the Streamlit port
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "Frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
